/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.Interfaces;

import javax.swing.JFrame;

/**
 *
 * @author carlo
 */
public class pantalla_inicio extends javax.swing.JFrame {

    /**
     * Creates new form pantalla_inicio
     */
    public pantalla_inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_informe = new javax.swing.JButton();
        btn_recibo = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        fondo_inicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_informe.setBackground(new java.awt.Color(230, 227, 213));
        btn_informe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_informe.setForeground(new java.awt.Color(31, 36, 55));
        btn_informe.setText("INFORME");
        btn_informe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_informeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_informeMouseExited(evt);
            }
        });
        btn_informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_informeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_informe, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 120, 70));

        btn_recibo.setBackground(new java.awt.Color(230, 227, 213));
        btn_recibo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_recibo.setForeground(new java.awt.Color(31, 36, 55));
        btn_recibo.setText("RECIBO");
        btn_recibo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_reciboMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_reciboMouseExited(evt);
            }
        });
        btn_recibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reciboActionPerformed(evt);
            }
        });
        getContentPane().add(btn_recibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 120, 70));

        btn_salir.setBackground(new java.awt.Color(230, 227, 213));
        btn_salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(31, 36, 55));
        btn_salir.setText("LOG OUT");
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 120, 70));

        fondo_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagen_fondo_inicio2.jpg"))); // NOI18N
        fondo_inicio.setText("jLabel1");
        getContentPane().add(fondo_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reciboActionPerformed
        // TODO add your handling code here:
        JFrame pantalla_empleado_recibo = new pantalla_empleado_recibo();
        pantalla_empleado_recibo.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_reciboActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        JFrame pantalla_login = new pantalla_login();
        pantalla_login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_informeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_informeActionPerformed
        // TODO add your handling code here:
        JFrame pantalla_informe_empleado = new pantalla_informe_empleado();
        pantalla_informe_empleado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_informeActionPerformed

    private void btn_reciboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reciboMouseEntered
        // TODO add your handling code here:
        btn_recibo.setBounds(135, 435, 130, 80);
    }//GEN-LAST:event_btn_reciboMouseEntered

    private void btn_reciboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reciboMouseExited
        // TODO add your handling code here:
         btn_recibo.setBounds(140, 440, 120, 70);
    }//GEN-LAST:event_btn_reciboMouseExited

    private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered
        // TODO add your handling code here:
         btn_salir.setBounds(425, 435, 130, 80);
    }//GEN-LAST:event_btn_salirMouseEntered

    private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited
        // TODO add your handling code here:
        btn_salir.setBounds(430, 440, 120, 70);
    }//GEN-LAST:event_btn_salirMouseExited

    private void btn_informeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_informeMouseEntered
        // TODO add your handling code here:
        btn_informe.setBounds(695, 435, 130, 80);
    }//GEN-LAST:event_btn_informeMouseEntered

    private void btn_informeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_informeMouseExited
        // TODO add your handling code here:
        btn_informe.setBounds(700, 440, 120, 70);
    }//GEN-LAST:event_btn_informeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla_inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_informe;
    private javax.swing.JButton btn_recibo;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel fondo_inicio;
    // End of variables declaration//GEN-END:variables
}
